version: "3.8"

services:
  django:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - django_static_volume:/usr/src/app/static
    ports: 
      - 8000:8000
    expose:
      - 8000
    env_file:
      - ./backend/.env
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - API_SERVER=${ENV_API_SERVER}
    volumes:
      - react_static_volume:/usr/src/app/build/static
    expose:
      - 3000
    env_file:
      - .env
    command: serve -s build -l 3000
    depends_on:
      - django

  nginx:
    restart: always
    build: ./nginx
    volumes:
      - django_static_volume:/usr/src/app/django_files/static
      - react_static_volume:/usr/src/app/static
    ports:
      - 8080:8080
    depends_on:
      - react
  #   # links: 
  #   #   - django

volumes:
#   postgres_data:
  django_static_volume:
  react_static_volume: